Implemented full-width support
HangfireIO/Hangfire pull request #1873
Opened 2021-06-07 10:01 UTC by danillewin

Before:
 
 Fixed width, even when screen width is wider than 1200px
 
 
![full-screen-before](https://user-images.githubusercontent.com/6246972/120997918-44e4de80-c790-11eb-8688-50e30950aad6.png)

After:

For screens wider than 1200px container width is now relative

![full-screen-1](https://user-images.githubusercontent.com/6246972/120998064-66de6100-c790-11eb-83e5-c10ff0bdae03.png)

![full-screen-2](https://user-images.githubusercontent.com/6246972/120998044-604fe980-c790-11eb-9eae-acd7e963f486.png)

2021-06-15 08:15 UTC, odinserj commented
Thanks @danillewin :+1:, will decide whether it should be available in 1.8.0 or in 1.7.24 and merge it.

2021-06-24 11:58 UTC, odinserj commented
Really awesome, can't wait to merge it. Is it ready to be merged?

2021-06-24 12:04 UTC, odinserj requested changes

2021-06-24 12:04 UTC, odinserj commented on src/Hangfire.Core/Dashboard/Content/css/hangfire.css
> +    padding-top: 70px
This rule deprecates the following one in line 9. Why it's not removed?

![image](https://user-images.githubusercontent.com/1078718/123259282-fad45a80-d4fc-11eb-8921-7697cd02e620.png)

2021-06-24 12:04 UTC, odinserj commented on src/Hangfire.Core/Dashboard/Content/css/hangfire.css
> +        padding-top: 75px
Why not make a choice and use either "70px" or "75px"? Is there any particular reason to use "70px" in one case and "75px" in another?

2021-06-24 12:04 UTC, odinserj commented on src/Hangfire.Core/Dashboard/Content/css/hangfire.css
> +    margin-bottom: -1px;
As far as I understand negative margins is a bad sign. Is it possible to avoid using it?

2021-06-24 12:04 UTC, odinserj commented on src/Hangfire.Core/Dashboard/Content/css/hangfire.css
> +    padding-left: 0;
Can you show us a screenshot with such an alert?

2021-06-24 12:04 UTC, odinserj commented on src/Hangfire.Core/Dashboard/Pages/LayoutPage.cshtml
> +                                        <span class="hidden-sm">
I think this is unrelated to the current PR. Please roll this back.

2021-06-24 13:38 UTC, danillewin commented on src/Hangfire.Core/Dashboard/Content/css/hangfire.css
> +    padding-left: 0;
Sure, here they are:
![image_2021-06-24_16-04-31](https://user-images.githubusercontent.com/6246972/123267758-09733f80-d506-11eb-9bca-54b4b8f6423d.png)

![image_2021-06-24_16-05-18](https://user-images.githubusercontent.com/6246972/123267771-0bd59980-d506-11eb-9bc9-7c163f8b9dea.png)

2021-06-24 13:38 UTC, danillewin commented on src/Hangfire.Core/Dashboard/Content/css/hangfire.css
> +    padding-top: 70px
It's my mistake, will fix it in next commit

2021-06-24 13:38 UTC, danillewin commented on src/Hangfire.Core/Dashboard/Pages/LayoutPage.cshtml
> +                                        <span class="hidden-sm">
Roll back in next commit

2021-06-24 13:38 UTC, danillewin commented on src/Hangfire.Core/Dashboard/Content/css/hangfire.css
> +    margin-bottom: -1px;
Yes, it's possible, but it's more complicated.

I did this negative margin to avoid navbar's bottom border

![Capture2](https://user-images.githubusercontent.com/6246972/123272145-26aa0d00-d50a-11eb-9bae-4db3a93c2e40.PNG)

It appears because navbar is parent for alert. So with negative margin we got this

![Capture](https://user-images.githubusercontent.com/6246972/123272248-42151800-d50a-11eb-817a-bbdfa574b280.PNG)

We can achieve same behavior by adding `border-bottom: none` for navbar when alert is visible, but I didn't want to change navbar.

I can implement it, if this is preferred

2021-06-24 13:41 UTC, odinserj commented on src/Hangfire.Core/Dashboard/Content/css/hangfire.css
> +        padding-top: 75px
Is it possible to use the same value?

2021-06-24 13:43 UTC, odinserj commented on src/Hangfire.Core/Dashboard/Content/css/hangfire.css
> +    margin-bottom: -1px;
Ah OK then, but please submit another PR for alert-fixed, because new alert will be released tomorrow, and full width support will be released in autumn.

2021-06-24 13:44 UTC, odinserj commented on src/Hangfire.Core/Dashboard/Pages/LayoutPage.cshtml
> +                                        <span class="hidden-sm">
Please submit a new PR for this, I will merge it tomorrow to release tomorrow.

2021-06-24 13:44 UTC, odinserj commented on src/Hangfire.Core/Dashboard/Content/css/hangfire.css
> +    padding-left: 0;
Thanks!

2021-06-24 20:11 UTC, danillewin commented on src/Hangfire.Core/Dashboard/Pages/LayoutPage.cshtml
> +                                        <span class="hidden-sm">
Sure, here it is: https://github.com/HangfireIO/Hangfire/pull/1887

2021-06-24 20:17 UTC, danillewin commented on src/Hangfire.Core/Dashboard/Content/css/hangfire.css
> +        padding-top: 75px
No, because horizontal paddings at <768 screens are thinner by Bootstrap's theme.

We could:

1) left them as is and do not change  top padding, screen below

![image](https://user-images.githubusercontent.com/6246972/123326676-31809400-d542-11eb-8362-ec17977b88be.png)

2) or left current solution

![image](https://user-images.githubusercontent.com/6246972/123326810-583eca80-d542-11eb-93ad-ff75a6f9bb22.png)


Since the difference between paddings is not crucial, I believe that we can follow the first option, need your choice

2021-06-28 14:26 UTC, danillewin commented on src/Hangfire.Core/Dashboard/Content/css/hangfire.css
> +    padding-top: 70px
Fixed here: https://github.com/HangfireIO/Hangfire/pull/1873/commits/6582529d51807049f0d6a0594cc99cc47132df4c

2021-06-28 14:26 UTC, danillewin commented on src/Hangfire.Core/Dashboard/Content/css/hangfire.css
> +        padding-top: 75px
@odinserj please, could you help me with this decision?

2021-07-02 12:35 UTC, odinserj commented
Thanks for making all the changes requested. I've also changed the base branch to `dev` to land the changes to the 1.8.0 release only (and not to 1.7.X), and merge conflicts appeared (please see the message above). Could you please try to fix those conflicts by merging the `dev` branch into the PR's one?

2021-07-02 12:37 UTC, danillewin commented
> Could you please try to fix those conflicts by merging the `dev` branch into the PR's one?

Sure! Started

2021-07-05 10:42 UTC, danillewin commented
Moved here:

https://github.com/HangfireIO/Hangfire/pull/1893

2021-07-05 10:42 UTC, closed without merging